# for development
version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/dev/app/Dockerfile
    volumes:
      - php-socket:/var/run/php-fpm
      - ./:/app:cached
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: ./docker/dev/web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - php-socket:/var/run/php-fpm
      - ./public/:/app/public:cached
  db:
    build:
      context: .
      dockerfile: ./docker/dev/db/Dockerfile
    environment:
      MYSQL_DATABASE: like_twitter
      MYSQL_USER: like_twitter
      MYSQL_PASSWORD: like_twitter
      MYSQL_ROOT_PASSWORD: like_twitter
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3307:3306'
  node:
    build:
      context: .
      dockerfile: ./docker/dev/node/Dockerfile
    volumes:
      - .:/build:cached
      - /build/node_modules
    working_dir: /build
    command: npm run watch-poll
volumes:
  db-data:
    driver: local
  php-socket:
    driver: local
